//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertRuleSilenceRule) DeepCopyInto(out *AlertRuleSilenceRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertRuleSilenceRule.
func (in *AlertRuleSilenceRule) DeepCopy() *AlertRuleSilenceRule {
	if in == nil {
		return nil
	}
	out := new(AlertRuleSilenceRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalyrAlertFile) DeepCopyInto(out *ScalyrAlertFile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalyrAlertFile.
func (in *ScalyrAlertFile) DeepCopy() *ScalyrAlertFile {
	if in == nil {
		return nil
	}
	out := new(ScalyrAlertFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalyrAlertFile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalyrAlertFileList) DeepCopyInto(out *ScalyrAlertFileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScalyrAlertFile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalyrAlertFileList.
func (in *ScalyrAlertFileList) DeepCopy() *ScalyrAlertFileList {
	if in == nil {
		return nil
	}
	out := new(ScalyrAlertFileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalyrAlertFileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalyrAlertFileSpec) DeepCopyInto(out *ScalyrAlertFileSpec) {
	*out = *in
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]ScalyrAlertRuleSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalyrAlertFileSpec.
func (in *ScalyrAlertFileSpec) DeepCopy() *ScalyrAlertFileSpec {
	if in == nil {
		return nil
	}
	out := new(ScalyrAlertFileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalyrAlertFileStatus) DeepCopyInto(out *ScalyrAlertFileStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalyrAlertFileStatus.
func (in *ScalyrAlertFileStatus) DeepCopy() *ScalyrAlertFileStatus {
	if in == nil {
		return nil
	}
	out := new(ScalyrAlertFileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalyrAlertRule) DeepCopyInto(out *ScalyrAlertRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalyrAlertRule.
func (in *ScalyrAlertRule) DeepCopy() *ScalyrAlertRule {
	if in == nil {
		return nil
	}
	out := new(ScalyrAlertRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalyrAlertRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalyrAlertRuleList) DeepCopyInto(out *ScalyrAlertRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScalyrAlertRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalyrAlertRuleList.
func (in *ScalyrAlertRuleList) DeepCopy() *ScalyrAlertRuleList {
	if in == nil {
		return nil
	}
	out := new(ScalyrAlertRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalyrAlertRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalyrAlertRuleSpec) DeepCopyInto(out *ScalyrAlertRuleSpec) {
	*out = *in
	if in.GracePeriodMinutes != nil {
		in, out := &in.GracePeriodMinutes, &out.GracePeriodMinutes
		*out = new(int32)
		**out = **in
	}
	if in.RenotifyPeriodMinutes != nil {
		in, out := &in.RenotifyPeriodMinutes, &out.RenotifyPeriodMinutes
		*out = new(int32)
		**out = **in
	}
	if in.ResolutionDelayMinutes != nil {
		in, out := &in.ResolutionDelayMinutes, &out.ResolutionDelayMinutes
		*out = new(int32)
		**out = **in
	}
	if in.Silences != nil {
		in, out := &in.Silences, &out.Silences
		*out = make([]AlertRuleSilenceRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalyrAlertRuleSpec.
func (in *ScalyrAlertRuleSpec) DeepCopy() *ScalyrAlertRuleSpec {
	if in == nil {
		return nil
	}
	out := new(ScalyrAlertRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalyrAlertRuleStatus) DeepCopyInto(out *ScalyrAlertRuleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalyrAlertRuleStatus.
func (in *ScalyrAlertRuleStatus) DeepCopy() *ScalyrAlertRuleStatus {
	if in == nil {
		return nil
	}
	out := new(ScalyrAlertRuleStatus)
	in.DeepCopyInto(out)
	return out
}
