# permissions for end users to view scalyralertfiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scalyralertfile-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: scalyr-k8s-operator
    app.kubernetes.io/part-of: scalyr-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: scalyralertfile-viewer-role
rules:
- apiGroups:
  - alerts.scalyr.com
  resources:
  - scalyralertfiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alerts.scalyr.com
  resources:
  - scalyralertfiles/status
  verbs:
  - get
